### ISSUE TITLE
Maybe incorporate at least vsearchvec into PDL::Primitive?

### ISSUE THREAD

**Issue by mohawk2** [moocow-the-bovine/PDL-VectorValued#5]
As shown in the in-`master`-but-not-CPAN-yet [PDL::IO::STL](https://github.com/PDLPorters/pdl/blob/ef05792260dbdbfe7b057e5571a98bec4d5ab97a/IO/STL/STL.pm#L150-L158), for space-efficiency (as well as conceptual correctness), and therefore deduplicating of triangle-vertex coordinates, it is essential to use `vsearchvec` - main PDL doesn't have such a thing, which is undoubtedly why you created it.

Would you be open to contributing the functions/operations in this distribution to PDL::Primitive (with credit, obviously)? Among the issues this might cause, I can see that it would make it difficult for your consuming code if you wanted to stick with PDL 2.019, unless you didn't mind the overlapping functions existing both in main PDL and your module (conceivably you might do a version-of-PDL dependent load/import).

**Comment by mohawk2** [comment]
On a connected matter: I added a `cmpvec` to PDL::Primitive, and Debian's automated package testing sees the warnings from that being redefined by P:VV, and refuses to package the latest PDL: https://qa.debian.org/excuses.php?package=pdl

**Comment by mohawk2** [comment]
I've fixed this in PDL by renaming `eqvec` and `cmpvec` to `veceq` and `veccmp`.

**Comment by moocow-the-bovine** [comment]
apologies for the delayed response: I'd love to help get vesearchvec &c into PDL::Primitive, and can certainly tweak PDL::VectorValued with any necesasry accomodations.  I think it would be wise (if we're moving vsearchvec) to move some of the PDL::VectorValued::Utils macros into PDL::PP as well, but it's not strictly necessary.  I haven't really had any time to look into this yet (it's raining bugs), and don't foresee much this weekend either.

**Comment by mohawk2** [comment]
Great to hear back from you! If you want more eyes on bugs in PDL stuff (including yours that have Zaki's amazing CI), please open issues on those with all the info you have, and we'll see them in the IRC channel and that increases greatly the chance of getting help.

The major accommodation I'd need is for current VV (and its dependents, at least CCS) to deconflict the names with PDL. You obviously chose your names very well, and in the obvious way to fit in with the PDL conventions, i.e. with `vec` on the end.

If you were comfortable doing this, then I'd ask you to prepend `vv_` in front of your versions, and release updates to CPAN (updating your downstream modules to depend on the updated VV). With that done (and the Debian-packaged versions updated), I could then update main PDL to include probably all of VV::Utils with the same (or similar, I haven't looked closely yet) names, crediting you in the docs. If back-compat is a concern, you could have a PDL-version-dependent alias without the `vv_`, adding that to exports.

**Comment by moocow-the-bovine** [comment]
> renaming eqvec and cmpvec to veceq and veccmp.

probably not ideal (which I'm guessing is why you mentioned it): the existing PDL naming conventions seem to use `vec` as a suffix.

> update main PDL to include probably all of VV::Utils with the same (or similar, I haven't looked closely yet) names

thinking about this some more (and after some sleep), I've got to back down / revise my previous suggestion.  First of all, I was actually thinking of VV/Dev.pm (PDL::PP-level wrappers `vvpp_*`) when I wrote `VV::Utils` rather than VV::Utils itself (uses VV::Dev genenerate PDL::PP calls), which will be tricky to get into PP (although I seem to recall that you've recently added some functionality which ought to make that easier/possible, it will probably involve a good deal of non-trivial refactoring which I haven't yet had time to look into).

VV::Utils (the actual perl-level `PDL::vv_*` functions, including `vsearchvec`) only makes sense to port if the VV::Dev (or equivalent functionality) also exists in main PDL.  If that functionality is exposed (e.g. by `PDL::PP` or some optional plugin like `PDL::PP::VV` which one could `use` from `MODULE.pd` to get access to the PP macros), then `VV::Dev` will need to import & wrap that too.  Otherwise, we'll have code-duplication on the VV::Dev level (I'd prefer to avoid that).

> prepend vv_ in front of your versions, and release updates to CPAN

good plan, should be easy, added to my queue (near the front).

> PDL-version-dependent alias without the vv_

yup, should also be easy, will bundle with next VV release.

**Comment by moocow-the-bovine** [comment]
... another thought: my goal would be for VV-downstream modules such as `PDL::CCS` to continue to "just work" regardless of where the actual VV calls are living.  That means that the `VV::Utils` and `VV::Dev` namespaces would (for now) continue to exist as before, just wrapping the actual code in main PDL.

regarding back-compatibility: I've updated to bullseye now, so I'm at least at 2.025 ;-)

**Comment by mohawk2** [comment]
> regarding back-compatibility: I've updated to bullseye now, so I'm at least at 2.025 ;-)

Now if only I could persuade you to use `cpanm PDL`! ;-)

**Comment by mohawk2** [comment]
I'll respond more fully to your previous thoughts soon, but an immediate point: the relatively new `pp_add_macros` (in 2.064) is intended to allow one to add `$CMPVEC()` without needing at least that part of VV::Dev.

**Comment by mohawk2** [comment]
For the rest: I appreciate that VV::Utils has some need of VV::Dev, but my reading of it says it's about the additional macros (which PDL can now accommodate natively) and the back-compat for older PDLs (which obviously isn't a concern for main PDL). I will be completely happy with porting it into main PDL myself as soon as we achieve the name-deconfliction which only you can do.

Once that incorporation was done, I could then PR the update to VV to generate either the same stuff or the compat wrapper if on a new enough PDL. Of course, if you were persuadable on allowing depending on quite-new PDL, the older code could simply be evaporated!

**Comment by moocow-the-bovine** [comment]
@mohawk2 can you check out https://github.com/moocow-the-bovine/PDL-VectorValued/tree/localize-function-names and let me know if that's sufficient for you to move forward on the PDL core side?

The current setup only expects `cmpvec`, `eqvec` and `vesearchvec` to exist in PDL core, but it's easy to add more symbols to that category (`%VV_IMPORT`).

**Comment by mohawk2** [comment]
I looked at the PR you made from that and commented. If you're happy for me to do so, I'd like to bring over all of these:

- vsearchvec
- cmpvec
- rlevec
- rldvec

And conceivably also if and only if you think it's a good idea to do so:
- enumvec
- enumvecg
- rleseq
- rldseq

Also the vector union/setdiff/intersect functions, if and only if you think it's a good idea to do so. It does seem like a good idea to expand the vectors "vocabulary" of P:Primitive with those, but
 we'd need to think about the names of those. It looks to me like there's room to add them with `vec` on the end there (and `sortedvec` where it's that), and I'd add a `setopsvec` and `setopssortedvec` too. For those, and quite likely the current `setops`, I'd update to support broadcasting.

Your thoughts, as the PDL vector-valued stuff expert, extremely welcome!

**Comment by moocow-the-bovine** [comment]
> vsearchvec cmpvec rlevec rldvec

Yup, those sound like good candidates (although I'm not sure that `cmpvec` is genuinely useful on its own, it is a good "lowest bar").

> rleseq rldseq

Since these are generalizations of existing PDL functions, that also sounds wise

> enumvec enumvecg

I don't think PDL has equivalent functionality for flat ndarrays, and I'm not sure how useful these would be in PDL core.  I have certainly needed them in the past to keep track of vector-valued "vocabularies", and I think they might be useful to other folks working with discrete data (n-grams etc.), but they're pretty specialized.  If you're not concerned about introducing "clutter" into PDL::Primitive, I'm happy for these to move too.

> vector union/setdiff/intersect functions, if and only if you think it's a good idea to do so

Yes, I would tend to agree ... these too are generalizations of existing stuff in the PDL core.  As you note, the `vv_` naming conventions begin to wobble a bit here (although I could always rename e.g. `VV::Utils::vv_union` to `vv_vv_union`, which would be a bit goofy-looking but I could live with as a stopgap measure).  Calling the PDL core versions `unionvec` etc. seems more in line with the existing core naming conventions.  The VV-side symbol-table twiddling would require a bit more logic to handle that, or I could just deprecate those functions in VV until I raise the PDL dependency & can just alias them directly in VV::Utils a la qsortvec at https://github.com/moocow-the-bovine/PDL-VectorValued/blob/master/Utils/utils.pd#L451 .

... in light of all these potential changes, maybe I should just drop the `%VV_IMPORT` go-list & check (see 
https://github.com/moocow-the-bovine/PDL-VectorValued/pull/6/files#r873339913) ... what do you think?

**Comment by mohawk2** [comment]
My understanding of your current thinking is that you're happy for all the below-named functions, including the set-operations, to go into PDL::Primitive (and I now realise some should go into PDL::Slices with their non-vector equivalents). If you're content for me to incorporate them, then you'd include them in your deconflicting code.

I think it would be prudent for us to avoid doubt by spelling out the "now" and "future" scenarios (PVU=PDL::VV::Utils, P=PDL::Primitive, S=PDL::Slices):

|Now in PVU|Future in PVU|Future in PDL|
|-|-|-|
|rlevec|vv_rlevec|S::rlevec|
|rldvec|vv_rldvec|S::rldvec|
|rleseq|vv_rleseq|S::rleseq|
|rldseq|vv_rldseq|S::rldseq|
|enumvec|vv_enumvec|P::enumvec|
|enumvecg|vv_enumvecg|P::enumvecg|
|vsearchvec|vv_vsearchvec|P::vsearchvec|
|cmpvec|vv_cmpvec|P::cmpvec|
|vv_union|vv_union|P::unionvec|
|vv_intersect|vv_intersect|P::intersectvec|
|vv_setdiff|vv_setdiff|P::setdiffvec|
|v_union|v_union|P::union|
|v_intersect|v_intersect|P::intersect|
|v_setdiff|v_setdiff|P::setdiff|

The last 3 imply switching the current `P::setops` from being a number of calls to other things, to just being a wrapper for your code. The current forced flattening, which prevents broadcasting, will go. I don't think it's valuable to make a `setopsvec` equivalent, but am open to persuasion :-)

I believe the best way to achieve your intent is where main PDL (and you'd need to version-check) provides the third-column stuff, you'd then `require PDL::Primitive; require PDL::Slices` and symbol-alias those into PVU with their second-column name. My feeling is the most robust way to achieve this is to make a full mapping hash, rather than try rules-based stuff, since there's only 14 items. This is an update of my comments on #6 as I have thought more and conceivably better now :-)

I don't have an informed opinion on what that would mean for your `%VV_IMPORT` question, sorry!

**Comment by moocow-the-bovine** [comment]
> If you're content for me to incorporate them, then you'd include them in your deconflicting code.

yup, will do, thanks!

> I think it would be prudent for us to avoid doubt by spelling out the "now" and "future" scenarios

Many thanks for the explicit list!  Seeing it spelled out this way, I realize that it's probably best to make this explicit in the code too in order to minimize future maintenance headaches (which answers my `%VV_IMPORT` question :-)

> The last 3 imply switching the current `P::setops` from being a number of calls to other things, to just being a wrapper for your code.

I'm flattered to have my code included, but I'm not sure this is an entirely wise move: the setops functions from VV require that their arguments are *sorted*, while the equivalent functions in PDL::Primitive do not.  Changing that requirement would likely break any existing code using `P:setops` and `P:intersect`.  Adding an implicit `qsort()` in the new PDL::Primitive versions would keep the core back-compatible, but also remove the justification for my implementations (the Big Idea™ was that these things can run a bit faster if the user guarantees that the inputs are pre-sorted).   So if you want to include them, maybe they ought to be teased apart along the lines of:

|Now in PVU|Future in PVU|Future in PDL|
|-|-|-|
|v_union|v_union|P::sortedunion|
|v_intersect|v_intersect|P::sortedintersect|
|v_setdiff|v_setdiff|P::sortedsetdiff|

... and then `P::union` could wrap `sortedunion(qsort($a), qsort($b))` etc., and `setops` could wrap those wrappers.

> you'd then require PDL::Primitive; require PDL::Slices and symbol-alias those into PVU

I agree that the most robust way would be importing into PVU, but I'm going to stick with the symbol-table-twiddling in PV itself (without the `U`) for now nonetheless, for my own sanity's sake... if it's insufficient, I'll take full responsibility ;-)

> you'd then require `PDL::Primitive; require PDL::Slices`

The top-level PDL::VectorValued already does a `use PDL;`, which ought to (if I understand correctly) take care of the core-internal aliases like `*PDL::cmpvec = *PDL::Primitive::cmpvec`, so VV can just check if `*PDL::cmpvec` is defined and use whatever it's bound to.

**Comment by moocow-the-bovine** [comment]
- updated PR https://github.com/moocow-the-bovine/PDL-VectorValued/pull/6 with expected aliases a la https://github.com/moocow-the-bovine/PDL-VectorValued/issues/5#issuecomment-1129226192 modulo https://github.com/moocow-the-bovine/PDL-VectorValued/issues/5#issuecomment-1129344334
- if you have no objections, I'll merge & release tomorrow

**Comment by mohawk2** [comment]
> [...] P::sortedunion

I think it would be better to go with `P::union_sorted` etc, how about you?

> > you'd then require PDL::Primitive; require PDL::Slices and symbol-alias those into PVU
> 
> I agree that the most robust way would be importing into PVU, but I'm going to stick with the symbol-table-twiddling in PV itself (without the `U`) for now nonetheless, for my own sanity's sake... if it's insufficient, I'll take full responsibility ;-)

I'm entirely happy for you to manage your own package/distro! I hadn't fully looked into how/where you defined functions etc.

> > you'd then require `PDL::Primitive; require PDL::Slices`
> 
> The top-level PDL::VectorValued already does a `use PDL;`, which ought to (if I understand correctly) take care of the core-internal aliases like `*PDL::cmpvec = *PDL::Primitive::cmpvec`, so VV can just check if `*PDL::cmpvec` is defined and use whatever it's bound to.

I'd missed the `use PDL`; you do indeed understand correctly, so that's fine.

In terms of releasing, do you think it would be prudent to get a PDL 2.080 ready for trying out, or are you content to "release often" if there's anything we need to tweak?

**Comment by moocow-the-bovine** [comment]
> > [...] P::sortedunion
> 
> I think it would be better to go with `P::union_sorted` etc, how about you?

Sounds good, expectations updated in the code.

> In terms of releasing, do you think it would be prudent to get a PDL 2.080 ready for trying out, or are you content to "release often" if there's anything we need to tweak?

I'm happy to go with "release often" for VV, since there's not much administrative baggage involved with that (less than I imagine there is for PDL itself).

**Comment by moocow-the-bovine** [comment]
uploaded to CPAN as v1.0.19

**Comment by mohawk2** [comment]
I'm just updating PDL now, including fetching the latest P:VV. IRC tells me you tagged 1.0.19, but a `pull` isn't bringing that to my repo?

**Comment by moocow-the-bovine** [comment]
the full tag is `PDL-VectorValued-1.0.19`: https://github.com/moocow-the-bovine/PDL-VectorValued/releases/tag/PDL-VectorValued-1.0.19

**Comment by mohawk2** [comment]
The commit for that is https://github.com/moocow-the-bovine/PDL-VectorValued/commit/4bcf7d858f78a90854332d061cdd0485a475f849 which you'll see says `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository`. I suspect you've not pushed something from `master`. I'd still have expected it to get pulled as a tag to my local, so I've learned now it doesn't do that.

**Comment by mohawk2** [comment]
By the way, the two `setdiff` functions look a bit strange in their sizing of `NC`; surely the maximum size of the diff is `NA + NB`, not `NA`?

**Comment by moocow-the-bovine** [comment]
bizarre.  I had indeed neglected to `git push` 1 commit.  I've now done that, deleted & re-tagged. both `master` and `PDL-VectorValued-1.0.19` should now point to 4bcf7d8 .  Sorry for the wonk-up.

> By the way, the two setdiff functions look a bit strange in their sizing of NC; surely the maximum size of the diff is NA + NB, not NA?

I don't believe so (= I'm very confident). The maximum-size result of `A \ B` is the case where `B == ø` so `A \ B == A` and `max(|A \ B|) = |A|`.  Informally, `setdiff` can only remove stuff that's already in `A`, and never adds anything.

[EDIT: intersection is a bit trickier, since `max(|A ∩ B|) = min(|A|, |B|)` ... maybe a case for `RedoDimsCode`]

**Comment by mohawk2** [comment]
> bizarre. I had indeed neglected to `git push` 1 commit. I've now done that, deleted & re-tagged. both `master` and `PDL-VectorValued-1.0.19` should now point to [4bcf7d8](https://github.com/moocow-the-bovine/PDL-VectorValued/commit/4bcf7d858f78a90854332d061cdd0485a475f849) . Sorry for the wonk-up.

Didn't cause any real problems!

> > By the way, the two setdiff functions look a bit strange in their sizing of NC; surely the maximum size of the diff is NA + NB, not NA?
> 
> I don't believe so (= I'm very confident). The maximum-size result of `A \ B` is the case where `B == ø` so `A \ B == A` and `max(|A \ B|) = |A|`. Informally, `setdiff` can only remove stuff that's already in `A`, and never adds anything.

Ah, the function name isn't very clear (to me). I was thinking it was the union minus the intersection, which is what the current `setops` "XOR" thing does.

And, in line with your update, it does look like the intersection needs that `RedoDimsCode`. I will take a look once I have finished making the `$CMPVEC()` work.

That's actually quite complicated because the current macro system, unlike yours, just passes a string to the macro sub, whereas what I think it should do is split on not-inside-brackets commas, like the C preprocessor does. It also needs to change from doing its macro expansion *after* the code has got parsed to *before*, so I can do `$CMPVEC($a(), ...)` and the `$a()` can expand Ok being inside a `loop ($dimname) %{ ... %}`.

**Comment by moocow-the-bovine** [comment]
>  I was thinking it was the union minus the intersection, which is what the current setops "XOR" thing does.

Ah, that makes sense... yeah, `XOR` is something else (`(A ∪ B) \ (A ∩ B)`); `setdiff` is really just `A \ B` .

**Comment by mohawk2** [comment]
And indeed on re-reading, the `RedoDimsCode` I've got here (it's the post-2.075 one, obviously) for the intersect functions, I'll adjust them just to use `PDLMIN()` because that's a bit shorter and clearer. Thanks!

**Comment by mohawk2** [comment]
I've completed the incorporation, commit https://github.com/PDLPorters/pdl/commit/e9784e4c330cf445e6dd977a98dca21b6a752c4c - could you take a look? I made the following changes:
- switched to the >=2.075 `RedoDimsCode`
- switched some types to `PDL_Indx`/`indx`
- adjusted for my version of `$CMPVEC()`
- updated the tests

I also actually included `rleND` and `rldND` despite it not being as discussed above - would you like me to remove it? PDL as-is can't be released until either a) I remove them again; b) you put out a P:VV with them also included in the "import from PDL" gang.

**Comment by moocow-the-bovine** [comment]
> put out a P:VV with them also included in the "import from PDL" gang.

added & released as VV 1.0.20 to CPAN, in master & tagged as `PDL-VectorValued-1.0.20`

**Comment by mohawk2** [comment]
Apart from issues with warnings / Debian in #7 this is done, so closing!
